name: Agri Market Data Pipeline (Every 3 Hours)

on:
  workflow_dispatch:    # manual run if needed
  schedule:
    - cron: "0 */3 * * *"   # every 3 hours

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run data collection
        env:
          DATA_GOV_API_KEY: ${{ secrets.DATA_GOV_API_KEY }}
        run: python fetch_data.py

      - name: Commit data & progress
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/
          git commit -m "Auto update agmarknet data (3h cycle)" || echo "No changes"
          git push
